name: melodia
description: "A minimal music player"
publish_to: 'none'
version: 4.0.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  cached_network_image: ^3.4.1
  http: ^1.2.2
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  just_audio: ^0.9.42
  ionicons: ^0.2.2
  audio_video_progress_bar: ^2.0.3
  rxdart: ^0.28.0
  just_audio_background: ^0.0.1-beta.13
  dio: ^5.7.0
  audiotagger: ^2.2.1
  onesignal_flutter: ^5.2.7
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/social/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro