name: melodia
description: "A minimal Music Streaming/Downloader/Player App"
publish_to: 'none'
version: 3.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  cached_network_image: ^3.3.1
  just_audio: ^0.9.38
  just_audio_background:
  audio_video_progress_bar: ^2.0.3
  swipe_to: ^1.0.6
  permission_handler: ^11.3.1
  dio: ^5.4.3+1
  hive:
  hive_flutter:
  path_provider:
  flutter_localization:
  flutter_riverpod:
  riverpod_annotation:
  provider: ^6.1.2
  flutter_phoenix: ^1.1.1
  audiotagger: ^2.2.1
  tuple: ^2.0.2
  url_launcher: ^6.3.0
  onesignal_flutter: ^5.2.2
  firebase_core: ^3.1.1
  workmanager: ^0.5.2
  logger: ^2.3.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:
  riverpod_generator:
  riverpod_lint:
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/user.png
    - assets/chevron.png
    - assets/playlist_art.png
    - assets/song_thumb.png